### PR TITLE
Updated package-lock.json for upgraded node-forge.

### PR DESCRIPTION
**Pull request by firmusoft**
To fix vulnerability in the package-lock.json.

### CODE REVIEW

**Comment by melgish** [comment]
Why is there no matching change in package.json?

**Comment by firmusoft** [comment]
@melgish,

More than a couple of times we missed to check in package-lock.json and so there is no change in the package.json which is uptodate, but package-lock.json is not the latest.

**Comment by melgish** [comment]
I'm in the middle of creating/testing a release.  I will update package-lock.json as part of that.

**Comment by melgish** [comment]
package updates were included in 0.0.7 release

**Pull request closed without merging**
